# Generated by Django 5.1 on 2024-08-12 14:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id_cat', models.AutoField(primary_key=True, serialize=False)),
                ('tipo_cat', models.CharField(max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Clientes',
            fields=[
                ('id_cli', models.CharField(max_length=13, primary_key=True, serialize=False)),
                ('nombre_cli', models.CharField(max_length=50)),
                ('correo_cli', models.CharField(max_length=50)),
                ('direccion_cli', models.CharField(max_length=50)),
                ('estatura_cli', models.CharField(max_length=13, null=True)),
                ('fono', models.CharField(max_length=13, null=True)),
                ('is_deleted', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Mecanico',
            fields=[
                ('id_mec', models.CharField(max_length=13, primary_key=True, serialize=False)),
                ('nombre_mec', models.CharField(max_length=40)),
                ('correo_mec', models.CharField(max_length=40)),
                ('direc_mec', models.CharField(max_length=100)),
                ('expdf_mec', models.FileField(blank=True, upload_to='pdfsmecanicos')),
            ],
        ),
        migrations.CreateModel(
            name='Repuesto',
            fields=[
                ('id_rep', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('nombre_rep', models.CharField(max_length=255)),
                ('precio_rep', models.CharField(max_length=7)),
                ('proveedor_rep', models.CharField(max_length=20)),
                ('marca_rep', models.CharField(max_length=50)),
                ('descripcion_rep', models.TextField()),
                ('cantidad', models.IntegerField(default=1)),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=150, unique=True)),
                ('nombre', models.CharField(max_length=30)),
                ('apellido', models.CharField(max_length=30)),
                ('telefono', models.CharField(blank=True, max_length=15, null=True)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('password', models.CharField(max_length=128)),
                ('rol', models.CharField(choices=[('ADMINISTRADOR', 'Administrador'), ('MECANICO', 'Mecánico')], max_length=20)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Bicicleta',
            fields=[
                ('id_bic', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('color_bic', models.CharField(max_length=20)),
                ('marca_bic', models.CharField(max_length=30)),
                ('descripcion_bic', models.TextField()),
                ('tipo_bic', models.CharField(max_length=40)),
                ('estado_bic', models.CharField(max_length=40)),
                ('fotografia', models.FileField(blank=True, upload_to='bicicleta')),
                ('is_deleted', models.BooleanField(default=False)),
                ('cliente', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.PROTECT, to='ordenes.clientes')),
            ],
        ),
        migrations.CreateModel(
            name='Orden',
            fields=[
                ('id_ord', models.AutoField(primary_key=True, serialize=False)),
                ('descripcion_ord', models.TextField()),
                ('fecha_ord', models.DateField(null=True)),
                ('bicicleta', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.PROTECT, to='ordenes.bicicleta')),
                ('mecanico', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.PROTECT, to='ordenes.mecanico')),
                ('fkusuario', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.PROTECT, to='ordenes.usuario')),
            ],
        ),
        migrations.CreateModel(
            name='Detalle',
            fields=[
                ('id_det', models.AutoField(primary_key=True, serialize=False)),
                ('entrega_det', models.DateField(null=True)),
                ('metodoPago_det', models.CharField(max_length=30, null=True)),
                ('estado_det', models.CharField(max_length=20, null=True)),
                ('total_det', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ('orden', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.PROTECT, to='ordenes.orden')),
                ('fkrepuestos', models.ManyToManyField(blank=True, to='ordenes.repuesto')),
            ],
        ),
        migrations.CreateModel(
            name='Orden_Detalle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fkdetalle', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='ordenes.detalle')),
                ('fkorden', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='ordenes.orden')),
            ],
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id_pro', models.CharField(max_length=13, primary_key=True, serialize=False)),
                ('nombre_pro', models.CharField(max_length=100, null=True)),
                ('cantidad_pro', models.FloatField()),
                ('descripcion_pro', models.CharField(max_length=400, null=True)),
                ('ftprodu', models.FileField(blank=True, upload_to='producto')),
                ('fkcategoria', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.PROTECT, to='ordenes.categoria')),
            ],
        ),
        migrations.AddField(
            model_name='mecanico',
            name='fkusuario',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.PROTECT, to='ordenes.usuario'),
        ),
    ]
