# Generated by Django 5.0.6 on 2024-08-17 19:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ordenes', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bicicleta',
            name='estado_bic',
        ),
        migrations.AddField(
            model_name='bicicleta',
            name='accesorios_bic',
            field=models.CharField(max_length=40, null=True),
        ),
        migrations.AddField(
            model_name='bicicleta',
            name='grupo_bic',
            field=models.CharField(max_length=40, null=True),
        ),
        migrations.AddField(
            model_name='bicicleta',
            name='talla_bic',
            field=models.CharField(max_length=40, null=True),
        ),
        migrations.AddField(
            model_name='clientes',
            name='apellido_cli',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='usuario',
            name='ci_us',
            field=models.CharField(max_length=13, null=True),
        ),
        migrations.AlterField(
            model_name='bicicleta',
            name='cliente',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='ordenes.clientes'),
        ),
        migrations.AlterField(
            model_name='bicicleta',
            name='color_bic',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='bicicleta',
            name='fotografia',
            field=models.FileField(blank=True, null=True, upload_to='bicicleta'),
        ),
        migrations.AlterField(
            model_name='bicicleta',
            name='marca_bic',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='bicicleta',
            name='tipo_bic',
            field=models.CharField(max_length=40, null=True),
        ),
        migrations.AlterField(
            model_name='detalle',
            name='orden',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='ordenes.orden'),
        ),
        migrations.AlterField(
            model_name='mecanico',
            name='expdf_mec',
            field=models.FileField(blank=True, null=True, upload_to='pdfsmecanicos'),
        ),
        migrations.AlterField(
            model_name='mecanico',
            name='fkusuario',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='ordenes.usuario'),
        ),
        migrations.AlterField(
            model_name='orden',
            name='bicicleta',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='ordenes.bicicleta'),
        ),
        migrations.AlterField(
            model_name='orden',
            name='fkusuario',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='ordenes.usuario'),
        ),
        migrations.AlterField(
            model_name='orden',
            name='mecanico',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='ordenes.mecanico'),
        ),
        migrations.AlterField(
            model_name='producto',
            name='fkcategoria',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='ordenes.categoria'),
        ),
        migrations.AlterField(
            model_name='producto',
            name='ftprodu',
            field=models.FileField(blank=True, null=True, upload_to='producto'),
        ),
        migrations.AlterField(
            model_name='repuesto',
            name='marca_rep',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='repuesto',
            name='nombre_rep',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='repuesto',
            name='precio_rep',
            field=models.CharField(max_length=7, null=True),
        ),
        migrations.AlterField(
            model_name='repuesto',
            name='proveedor_rep',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
